export {
  defaultDesktopAgentProvider,
  defaultDesktopAgentConversationDetailMode,
  defaultDesktopAppCatalogChannel,
  defaultDesktopBrowserUseConnectionMode,
  defaultDesktopDockIconStyle,
  defaultDesktopDockPlacement,
  defaultDesktopFeatureFlags,
  defaultDesktopWorkspaceUiMode,
  defaultDesktopFileDefaultOpenersByExtension,
  defaultDesktopMinimizeAnimation,
  defaultDesktopProxySettings,
  defaultDesktopShowAppDeveloperSources,
  defaultDesktopSleepPreventionMode,
  defaultDesktopUpdateChannel,
  defaultDesktopUpdatePolicy,
  defaultDesktopWorkbenchShortcuts,
  defaultDesktopWorkbenchWindowSnapping,
  desktopAgentComposerDefaultsByAgentTargetEqual,
  desktopAgentComposerDefaultsByProviderEqual,
  desktopAgentComposerDefaultsEqual,
  desktopAgentComposerDefaultsFields,
  desktopAgentGuiConversationRailCollapsedByProviderEqual,
  desktopAgentProviders,
  desktopDefaultAgentProviders,
  desktopAgentConversationDetailModes,
  desktopWorkspaceUiModes,
  desktopAppCatalogChannels,
  desktopBrowserUseConnectionModes,
  desktopDockIconStyles,
  desktopDockPlacements,
  desktopFeatureFlagsEqual,
  desktopFileDefaultOpeners,
  desktopFileDefaultOpenersByExtensionEqual,
  desktopMinimizeAnimations,
  desktopProxyModes,
  desktopProxySettingsEqual,
  desktopSleepPreventionModes,
  desktopUpdateChannels,
  desktopUpdatePolicies,
  desktopWorkbenchShortcutsEqual,
  desktopWorkbenchWindowSnappingEqual,
  desktopWorkbenchWindowSnappingShortcutPresets,
  formatDesktopShortcutBinding,
  isDesktopAgentProvider,
  isDesktopDefaultAgentProvider,
  isDesktopAgentConversationDetailMode,
  isDesktopAppCatalogChannel,
  isDesktopBrowserUseConnectionMode,
  isDesktopDockIconStyle,
  isDesktopDockPlacement,
  isDesktopFileDefaultOpener,
  isDesktopMinimizeAnimation,
  isDesktopProxyMode,
  isDesktopSleepPreventionMode,
  isDesktopUpdateChannel,
  isDesktopUpdatePolicy,
  isDesktopWorkbenchWindowSnappingShortcutPreset,
  mergeDesktopAgentComposerDefaultsByAgentTarget,
  mergeDesktopAgentComposerDefaultsByProvider,
  mergeDesktopAgentGuiConversationRailCollapsedByProvider,
  normalizeDesktopAgentComposerDefaults,
  normalizeDesktopAgentComposerDefaultsByAgentTarget,
  normalizeDesktopAgentComposerDefaultsByProvider,
  normalizeDesktopAgentConversationDetailMode,
  normalizeDesktopFileDefaultOpenersByExtension,
  normalizeDesktopFileExtension,
  normalizeDesktopAgentGuiConversationRailCollapsedByProvider,
  normalizeDesktopFeatureFlags,
  normalizeDesktopProxySettings,
  normalizeDesktopShortcutKey,
  normalizeDesktopWorkbenchShortcuts,
  normalizeDesktopWorkbenchWindowSnapping,
  readInitialDockPlacementFromLocation,
  type DesktopAgentComposerDefaults,
  type DesktopAgentComposerDefaultsByAgentTarget,
  type DesktopAgentComposerDefaultsByProvider,
  type DesktopAgentComposerDefaultsPatch,
  type DesktopAgentGuiConversationRailCollapsedByProvider,
  type DesktopAgentProvider,
  type DesktopDefaultAgentProvider,
  type DesktopAgentConversationDetailMode,
  type DesktopAppCatalogChannel,
  type DesktopBrowserUseConnectionMode,
  type DesktopDockIconStyle,
  type DesktopDockPlacement,
  type DesktopFeatureFlags,
  type DesktopWorkspaceUiMode,
  type DesktopFileDefaultOpener,
  type DesktopFileDefaultOpenersByExtension,
  type DesktopMinimizeAnimation,
  type DesktopProxyMode,
  type DesktopProxySettings,
  type DesktopSleepPreventionMode,
  type DesktopUpdateChannel,
  type DesktopUpdatePolicy,
  type DesktopWorkbenchShortcuts,
  type DesktopWorkbenchWindowSnapping,
  type DesktopWorkbenchWindowSnappingShortcutPreset
} from "./core.ts";
