export {
  agentGuiWorkbenchComingSoonProviders as workspaceAgentGuiComingSoonProviders,
  agentGuiWorkbenchDefaultDockProviders as workspaceAgentGuiDefaultDockProviders,
  agentGuiWorkbenchDockSuppressedProviders as workspaceAgentGuiDockSuppressedProviders,
  agentGuiWorkbenchProviderLabels as workspaceAgentGuiLabels,
  agentGuiWorkbenchPreviewProviders as workspaceAgentGuiPreviewProviders,
  agentGuiWorkbenchProviders as workspaceAgentGuiProviders,
  isAgentGuiWorkbenchComingSoonProvider as isWorkspaceAgentGuiComingSoonProvider,
  isAgentGuiWorkbenchDefaultDockProvider as isWorkspaceAgentGuiDefaultDockProvider,
  isAgentGuiWorkbenchDockSuppressedProvider as isWorkspaceAgentGuiDockSuppressedProvider,
  isAgentGuiWorkbenchPreviewProvider as isWorkspaceAgentGuiPreviewProvider,
  isAgentGuiWorkbenchProviderVisibleWithPreview as isWorkspaceAgentGuiProviderVisibleWithPreview,
  resolveAgentGuiWorkbenchProviderLabel as resolveWorkspaceAgentGuiLabel
} from "@tutti-os/agent-gui/workbench/providerCatalog";
