// Code generated by tools/scripts/generate-agent-live-protocol.mjs. DO NOT EDIT.

package liveprotocol

const ProtocolRevision = "sha256:8474280d7426e57b"

// Protobuf-wire field numbers and delivery kinds are generated from
// schema/agent-activity-live-wire-contract.json. They participate in
// ProtocolRevision and must not be edited independently.
const (
	frameRevisionField              = 1 // protocolRevision: bytes
	frameStreamIDField              = 2 // streamId: bytes
	frameBindingIDField             = 3 // bindingId: bytes
	frameEpochField                 = 4 // epoch: varint
	frameDeliveriesField            = 5 // deliveries: bytes
	deliverySeqField                = 1 // seq: varint
	deliveryKindField               = 2 // kind: varint
	deliveryEventField              = 3 // event: bytes
	deliveryDiscontinuityField      = 4 // discontinuity: bytes
	deliveryAttachmentField         = 5 // attachmentChanged: bytes
	deliveryGoalField               = 6 // goalChanged: bytes
	deliveryReadyField              = 7 // streamReady: bytes
	deliveryRejectedField           = 8 // rejected: bytes
	deliveryAttachmentCaughtUpField = 9 // attachmentCaughtUp: bytes
)

const (
	DeliveryKindEvent              DeliveryKind = 1 // payload: event
	DeliveryKindDiscontinuity      DeliveryKind = 2 // payload: discontinuity
	DeliveryKindAttachmentChanged  DeliveryKind = 3 // payload: attachmentChanged
	DeliveryKindGoalChanged        DeliveryKind = 4 // payload: goalChanged
	DeliveryKindStreamReady        DeliveryKind = 5 // payload: streamReady
	DeliveryKindRejected           DeliveryKind = 6 // payload: rejected
	DeliveryKindAttachmentCaughtUp DeliveryKind = 7 // payload: attachmentCaughtUp
)
